name: Java CI CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Create output directory
        run: mkdir -p out

      - name: Compile Java code
        run: javac -d out src/Main.java

      - name: Create JAR file
        run: jar cfe app.jar Main -C out .

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-jar-artifact
          path: app.jar

  release:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-jar-artifact
          path: output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: output/app.jar
